### ISSUE TITLE
v1.1.2 no rules expected / `Flags` build errors

### ISSUE THREAD

**Issue by probablykasper** [polyfloyd/rust-id3#93]
Got a build error when upgrading from 1.1.1 to 1.1.2
```
error: no rules expected the token `struct`
  --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:27:5
   |
27 |     struct ExtFlags: u8 {
   |     ^^^^^^ no rules expected this token in macro call

error[E0433]: failed to resolve: use of undeclared type `Flags`
  --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:88:57
   |
88 |         if version == Version::Id3v22 && flags.contains(Flags::COMPRESSION) {
   |                                                         ^^^^^ use of undeclared type `Flags`

error[E0433]: failed to resolve: use of undeclared type `Flags`
  --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:96:29
   |
96 |         dbg!(flags.contains(Flags::EXTENDED_HEADER));
   |                             ^^^^^ use of undeclared type `Flags`

error[E0433]: failed to resolve: use of undeclared type `Flags`
  --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:97:49
   |
97 |         let ext_header_size = if flags.contains(Flags::EXTENDED_HEADER) {
   |                                                 ^^^^^ use of undeclared type `Flags`

error[E0433]: failed to resolve: use of undeclared type `ExtFlags`
   --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:109:30
    |
109 |             let _ext_flags = ExtFlags::from_bits_truncate(ext_header[5]);
    |                              ^^^^^^^^ use of undeclared type `ExtFlags`

error[E0433]: failed to resolve: use of undeclared type `Flags`
   --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:142:38
    |
142 |             if header.flags.contains(Flags::UNSYNCHRONISATION) {
    |                                      ^^^^^ use of undeclared type `Flags`

error[E0433]: failed to resolve: use of undeclared type `Flags`
   --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:151:74
    |
151 |             let mut reader: Box<dyn io::Read> = if header.flags.contains(Flags::UNSYNCHRONISATION) {
    |                                                                          ^^^^^ use of undeclared type `Flags`

error[E0433]: failed to resolve: use of undeclared type `Flags`
   --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:298:19
    |
298 |         flags.set(Flags::UNSYNCHRONISATION, self.unsynchronisation);
    |                   ^^^^^ use of undeclared type `Flags`

error[E0433]: failed to resolve: use of undeclared type `Flags`
   --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:300:23
    |
300 |             flags.set(Flags::COMPRESSION, self.compression);
    |                       ^^^^^ use of undeclared type `Flags`

error[E0412]: cannot find type `Flags` in this scope
  --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:36:12
   |
36 |     flags: Flags,
   |            ^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
1  | use crate::stream::frame::v3::Flags;
   |
1  | use crate::stream::frame::v4::Flags;
   |

error[E0433]: failed to resolve: use of undeclared type `Flags`
  --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:83:21
   |
83 |         let flags = Flags::from_bits(header[5])
   |                     ^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
1  | use crate::stream::frame::v3::Flags;
   |
1  | use crate::stream::frame::v4::Flags;
   |

error[E0433]: failed to resolve: use of undeclared type `Flags`
   --> /Users/k/.cargo/registry/src/github.com-1ecc6299db9ec823/id3-1.1.2/src/stream/tag.rs:297:25
    |
297 |         let mut flags = Flags::empty();
    |                         ^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
1   | use crate::stream::frame::v3::Flags;
    |
1   | use crate::stream::frame::v4::Flags;
```

**Comment by polyfloyd** [comment]
What version of bitlflags has Cargo resolved for your project? It seems I silently started relying on behaviour present in bitflags v1.3. Easy fix, I will push a new update to also specify the minor version

**Comment by probablykasper** [comment]
Great, it's all good now, thank you!
