### ISSUE TITLE
build error below latest stable-1 ?

### ISSUE THREAD

**Issue by pinkforest** [polyfloyd/rust-id3#126]
There seems to be a problem with [content.rs:586:27](https://github.com/polyfloyd/rust-id3/blob/main/src/stream/frame/content.rs#L588)] related to changes with usize pattern-match exhaustiveness.

EDIT: It seems to work in 1.76 latest stable but in <= 1.74 this throws the pattern match on usize complaint

I reduced it to this [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7fb1d526f99a5ea505b15372864795b0)

There were some changes in rustc related to this a month or so back.. it seems precise matching didn't work <= 1.74

CI only uses the current stable which currently is 1.76 and it may or may not be feasible to support MSRV stable-2 ?

| Rustc | Result |
| :---      | :---        |
| 1.76   | Works |
| 1.75   | Works |
| 1.74   | Build fail |
| 1.73   | Build fail |
| 1.65   | Build fail |

 I raised #127 to wonder about the MSRV policy and whether this should be tested in CI given this is a library.

$ cargo build
```
    Updating crates.io index
... clip ...
   Compiling id3 v1.13.0 (..)
error[E0004]: non-exhaustive patterns: `_` not covered
   --> src/stream/frame/content.rs:586:27
    |
586 |             let r = match self.r.len() {
    |                           ^^^^^^^^^^^^ pattern `_` not covered
    |
    = note: the matched value is of type `usize`
    = note: `usize` does not have a fixed maximum value, so a wildcard `_` is necessary to match exhaustively
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
588 ~                 9.. => &self.r[..8],
589 ~                 _ => todo!(),
    |

For more information about this error, try `rustc --explain E0004`.
error: could not compile `id3` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `id3` (lib test) due to previous error
```

**Comment by polyfloyd** [comment]
Ah yes, that was introduced in 785a2710 because Clippy complained about it
